# Generated by Django 3.1.7 on 2021-03-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_vote',
            new_name='guest_can_pause',
        ),
    ]
